image:https://img.shields.io/travis/ccguyka/show-updates-maven-plugin/master[Travis,link=https://travis-ci.org/ccguyka/show-updates-maven-plugin]
image:https://sonarcloud.io/api/project_badges/measure?project=ccguyka_show-updates-maven-plugin&metric=alert_status[Sonar Quality Gate,link=https://sonarcloud.io/dashboard?id=ccguyka_show-updates-maven-plugin]
image:https://sonarcloud.io/api/project_badges/measure?project=ccguyka_show-updates-maven-plugin&metric=coverage[Sonar Coverage,link=https://sonarcloud.io/dashboard?id=ccguyka_show-updates-maven-plugin]
image:https://img.shields.io/github/last-commit/ccguyka/show-updates-maven-plugin[GitHub last commit,link=https://github.com/ccguyka/show-updates-maven-plugin/commits/master]
image:https://img.shields.io/snyk/vulnerabilities/github/ccguyka/show-updates-maven-plugin[Snyk Vulnerabilities for GitHub Repo,link=https://snyk.io/test/github/ccguyka/show-updates-maven-plugin]
image:https://img.shields.io/badge/License-MIT-yellow.svg[License: MIT,link=https://opensource.org/licenses/MIT]
image:https://img.shields.io/maven-central/v/com.github.ccguyka/show-updates-maven-plugin.svg[Maven Central,link=https://search.maven.org/search?q=g:com.github.ccguyka%20AND%20a:show-updates-maven-plugin]
image:http://www.0pdd.com/svg?name=ccguyka/show-updates-maven-plugin[0pdd,link=http://www.0pdd.com/p?name=ccguyka/show-updates-maven-plugin]

= Show Maven Updates Plugin

Show the latest update version of maven dependencies.

== Goals

=== Updates

The `updates` goal prints all dependencies to console and creates a `maven-updates.json` file for all maven modules.

----
mvn com.github.ccguyka:show-updates-maven-plugin:updates
----

==== Properties

|===
|name |default |description

|excludes |alpha,beta,SNAPSHOT |Dependency key words to be excluded from result as comma separated list
|versions |latest |Show either latest (patch, minor and major versions), major, minor or patch version updates.
|===

==== Example

This is how the output will look like. In this case the `guava-testlib` module of https://github.com/google/guava/tree/v27.0[guava] v27.0

----
[INFO] -------------------< com.google.guava:guava-testlib >-------------------
[INFO] Building Guava Testing Library 27.0-jre
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- show-updates-maven-plugin:updates (default-cli) @ guava-testlib ---
[INFO] Available parent updates:
[INFO]   com.google.guava:guava-parent ... 27.0-jre -> 27.0.1-jre, 27.1-jre, 29.0-jre
[INFO] Available dependency updates:
[INFO]   org.checkerframework:checker-qual ... 2.5.2 -> 2.5.8, 2.11.1, 3.3.0
[INFO]   com.google.errorprone:error_prone_annotations ... 2.2.0 -> 2.3.4
[INFO]   com.google.truth:truth ... 0.42 -> 0.46, 1.0.1
[INFO]   com.google.j2objc:j2objc-annotations ... 1.1 -> 1.3
[INFO]   junit:junit ... 4.12 -> 4.13
[INFO] Available plugin updates:
[INFO]   org.codehaus.mojo:animal-sniffer-maven-plugin ... 1.17 -> 1.18
----

=== Aggregate

The `aggregate` goal uses the created `maven-updates.json` of the `updates` goal and combines them into one `aggregated-maven-updates.json` within the root module.

----
mvn com.github.ccguyka:show-updates-maven-plugin:aggregate
----

=== Send report to slack

The `send-slack-message` goal will send the report to given https://api.slack.com/incoming-webhooks[slack webhook].

----
mvn com.github.ccguyka:show-updates-maven-plugin:send-slack-message -Dtoken=<slack-webhook>
----

== Developer notes

=== Build

How to build and test the project.

----
mvn test
----

=== Release deployment to central repository

Based on https://central.sonatype.org/pages/apache-maven.html#manually-releasing-the-deployment-to-the-central-repository[official documentation]

----
mvn release:clean release:prepare release:perform -Prelease
----
