image:https://img.shields.io/travis/ccguyka/show-updates-maven-plugin/master[Travis,link=https://travis-ci.org/ccguyka/show-updates-maven-plugin]
image:https://sonarcloud.io/api/project_badges/measure?project=ccguyka_show-updates-maven-plugin&metric=alert_status[Sonar Quality Gate,link=https://sonarcloud.io/dashboard?id=ccguyka_show-updates-maven-plugin]
image:https://sonarcloud.io/api/project_badges/measure?project=ccguyka_show-updates-maven-plugin&metric=coverage[Sonar Coverage,link=https://sonarcloud.io/dashboard?id=ccguyka_show-updates-maven-plugin]
image:https://img.shields.io/github/last-commit/ccguyka/show-updates-maven-plugin[GitHub last commit,link=https://github.com/ccguyka/show-updates-maven-plugin/commits/master]
image:https://img.shields.io/snyk/vulnerabilities/github/ccguyka/show-updates-maven-plugin[Snyk Vulnerabilities for GitHub Repo,link=https://snyk.io/test/github/ccguyka/show-updates-maven-plugin]
image:https://img.shields.io/badge/License-MIT-yellow.svg[License: MIT,link=https://opensource.org/licenses/MIT]
image:https://img.shields.io/maven-central/v/com.github.ccguyka/show-updates-maven-plugin.svg[Maven Central,link=https://search.maven.org/search?q=g:com.github.ccguyka%20AND%20a:show-updates-maven-plugin]
image:http://www.0pdd.com/svg?name=ccguyka/show-updates-maven-plugin[0pdd,link=http://www.0pdd.com/p?name=ccguyka/show-updates-maven-plugin]

= Show Maven Updates Plugin

Show the latest update version of maven dependencies.

== Goals

=== Updates

The `updates` goal prints all dependencies to console and creates a `maven-updates.json` file for all maven modules.

----
mvn com.github.ccguyka:show-updates-maven-plugin:updates
----

==== Properties

|===
|name |default |description

|excludes |alpha,beta,SNAPSHOT |Dependency key words to be excluded from result as comma separated list
|versions |major |Show either major or minor version updates.
|===

==== Example

This is how the output will look like. In this case the `guava-testlib` module of https://github.com/google/guava/tree/v27.0[guava] v27.0

----
[INFO] --------------------< com.google.guava:guava-tests >--------------------
[INFO] Building Guava Unit Tests 27.0-jre                                 [4/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- show-updates-maven-plugin:0.0.1-SNAPSHOT:updates (default-cli) @ guava-tests ---
[INFO] artifact com.google.guava:guava-testlib: checking for updates from central
[INFO] Available dependency updates:
[INFO]   org.checkerframework:checker-qual ... 2.5.2 -> 2.5.7
[INFO]   com.google.errorprone:error_prone_annotations ... 2.2.0 -> 2.3.2
[INFO]   org.easymock:easymock ... 3.0 -> 4.0.1
[INFO]   org.mockito:mockito-core ... 2.19.0 -> 2.23.0
[INFO] Available plugin updates:
[INFO]   org.apache.maven.plugins:maven-jar-plugin ... 3.0.2 -> 3.1.0
[INFO]   org.apache.maven.plugins:maven-source-plugin ... 2.1.2 -> 3.0.1
[INFO]   org.apache.maven.plugins:maven-surefire-plugin ... 2.7.2 -> 2.22.1
[INFO]   org.codehaus.mojo:build-helper-maven-plugin ... 1.7 -> 3.0.0
[INFO]   org.apache.maven.plugins:maven-compiler-plugin ... 3.6.1 -> 3.8.0
[INFO]   org.apache.maven.plugins:maven-deploy-plugin ... 2.8.2 -> 3.0.0-M1
[INFO] Available dependency management updates:
[INFO]   org.checkerframework:checker-qual ... 2.5.2 -> 2.5.7
[INFO]   com.google.errorprone:error_prone_annotations ... 2.2.0 -> 2.3.2
[INFO]   org.easymock:easymock ... 3.0 -> 4.0.1
[INFO]   org.mockito:mockito-core ... 2.19.0 -> 2.23.0
----

=== Aggregate

The `aggregate` goal uses the created `maven-updates.json` of the `updates` goal and combines them into one `aggregated-maven-updates.json` within the root module.

----
mvn com.github.ccguyka:show-updates-maven-plugin:aggregate
----

=== Send report to slack

The `send-slack-message` goal will send the report to given https://api.slack.com/incoming-webhooks[slack webhook].

----
mvn com.github.ccguyka:show-updates-maven-plugin:send-slack-message -Dtoken=<slack-webhook>
----

== Developer notes

=== Build

How to build and test the project.

----
mvn test
----

=== Release deployment to central repository

Based on https://central.sonatype.org/pages/apache-maven.html#manually-releasing-the-deployment-to-the-central-repository[official documentation]

----
mvn release:clean release:prepare release:perform -Prelease
----
